import { CollectionTheme, CollectionThemeId, CollectionTokens } from './CollectionTheme';
import { ShelfPresentation } from './themes/shelf/ShelfPresentation';
import { EditorialPresentation } from './themes/editorial/EditorialPresentation';
import { CinematicPresentation } from './themes/cinematic/CinematicPresentation';
import { GlassPresentation } from './themes/glass/GlassPresentation';
import { ShelfHeader, EditorialHeader, CinematicHeader, GlassHeader, CoverWallHeader } from './CollectionHeaders';
import { CoverWallCollectionView } from './themes/cover-wall/CoverWallCollectionView';

const base: CollectionTokens = { '--collection-bg': '#100d0b', '--collection-surface': '#211a15', '--collection-card-bg': '#231b14', '--collection-border': '#514032', '--collection-accent': '#a9d69a', '--collection-text': '#f1e9dc', '--collection-muted': '#c4b7a7', '--collection-shadow': '0 12px 28px #0007', '--collection-radius': '5px', '--collection-glow': 'rgba(233,171,89,.12)' };
export const collectionThemeRegistry: Record<CollectionThemeId, CollectionTheme> = {
  'cover-wall': { id: 'cover-wall', name: '封面墙', description: '封面铺满 · 沉浸浏览', layout: 'grid', backgroundTreatment: 'solid', cardVariant: 'cover', headerVariant: 'cover-wall', coversOnly: true, tokens: { ...base, '--collection-bg': '#050706', '--collection-surface': '#111612', '--collection-card-bg': '#0d100e', '--collection-border': '#344138', '--collection-accent': '#afc8a7', '--collection-text': '#edf1ea', '--collection-muted': '#a9b6aa', '--collection-shadow': 'none', '--collection-radius': '1px', '--collection-glow': '#afc8a724' }, Presentation: CoverWallCollectionView, Header: CoverWallHeader },
  shelf: { id: 'shelf', name: '木质唱片架', description: '温暖实体收藏感', layout: 'cabinet', backgroundTreatment: 'wood', cardVariant: 'sleeve', headerVariant: 'shelf', tokens: base, Presentation: ShelfPresentation, Header: ShelfHeader },
  editorial: { id: 'editorial', name: '极简画廊', description: '黑色策展陈列', layout: 'featured', backgroundTreatment: 'solid', cardVariant: 'cover', headerVariant: 'editorial', tokens: { ...base, '--collection-bg': '#080808', '--collection-surface': '#141414', '--collection-card-bg': 'transparent', '--collection-border': '#303030', '--collection-accent': '#a5c49d', '--collection-text': '#f4f3ef', '--collection-muted': '#b3b3ae', '--collection-shadow': 'none', '--collection-radius': '1px', '--collection-glow': 'transparent' }, Presentation: EditorialPresentation, Header: EditorialHeader },
  cinematic: { id: 'cinematic', name: '电影收藏', description: '沉浸式生活方式', layout: 'cinema', backgroundTreatment: 'photographic', cardVariant: 'sleeve', headerVariant: 'cinematic', tokens: { ...base, '--collection-bg': '#10100f', '--collection-surface': '#1c1c19', '--collection-card-bg': '#1b1b18', '--collection-border': '#3e3d34', '--collection-accent': '#c0d0a3', '--collection-text': '#f0eee5', '--collection-muted': '#bfbcac', '--collection-radius': '6px', '--collection-glow': 'rgba(205,161,96,.1)' }, Presentation: CinematicPresentation, Header: CinematicHeader },
  glass: { id: 'glass', name: '未来玻璃', description: '现代透明网格', layout: 'grid', backgroundTreatment: 'glass', cardVariant: 'sleeve', headerVariant: 'glass', tokens: { ...base, '--collection-bg': '#071412', '--collection-surface': '#10221d', '--collection-card-bg': 'rgba(25,49,41,.76)', '--collection-border': 'rgba(155,205,178,.2)', '--collection-accent': '#a4d6b4', '--collection-text': '#eaf5ee', '--collection-muted': '#b0c6ba', '--collection-shadow': '0 10px 30px rgba(0,0,0,.18)', '--collection-radius': '14px', '--collection-glow': 'rgba(111,181,139,.1)' }, Presentation: GlassPresentation, Header: GlassHeader },
};
export const collectionThemes = Object.values(collectionThemeRegistry);
