import React, { useEffect, useMemo, useRef, useState } from 'react';
import { BrowserMultiFormatReader, type IScannerControls } from '@zxing/browser';
import { ArrowLeft, Barcode, Camera, CameraOff, Check, ChevronDown, Disc3, Download, FileJson, GripVertical, ImagePlus, Library, Link2, LoaderCircle, Pencil, Plus, Search, Trash2, Upload } from 'lucide-react';
import { Album, Track, VinylType } from '../types';
import { AlbumSleeve } from './AlbumSleeve';
import { VinylDisc } from './VinylDisc';
import { audioEngine } from '../services/audioEngine';
import { PRESET_IMPORT_VINYLS, BARCODE_PRESET_MAP } from '../data/importPresets';
import { lookupVinylBarcode } from '../services/collectionApi';
import './ImportVinylModal.css';

interface ImportVinylModalProps { isOpen: boolean; onClose: () => void; onAddAlbum: (album: Album) => Promise<void>; onImportMultiple: (albums: Album[]) => Promise<void>; currentAlbums: Album[]; }
type Method = 'manual' | 'presets' | 'barcode' | 'batch';
type LpCount = 1 | 2 | 3 | 4;
const METHODS: { id: Method; label: string; icon: React.ElementType }[] = [{ id: 'manual', label: '手动录入', icon: Pencil }, { id: 'presets', label: '母盘库', icon: Library }, { id: 'barcode', label: '扫码', icon: Barcode }, { id: 'batch', label: 'JSON', icon: FileJson }];
const VINYL_TYPES: { value: VinylType; label: string; texture?: string }[] = [{ value: 'black', label: '黑胶' }, { value: 'colored', label: '彩胶', texture: 'red' }, { value: 'clear', label: '透明胶' }, { value: 'translucent', label: '半透明胶' }, { value: 'marble', label: '大理石纹', texture: 'marbled-01' }, { value: 'splatter', label: '泼墨胶', texture: 'splatter-01' }, { value: 'split', label: '分色胶', texture: 'split-01' }, { value: 'liquid', label: '液体胶', texture: 'liquid-01' }, { value: 'picture', label: '图片胶', texture: 'picture-base' }];
const GENRES = ['摇滚', '流行', '爵士', '电子', '古典', 'R&B', '嘻哈', '其他'];
const COLLECTION_TAGS = ['首版', '限量版', '彩胶', '签名版', '纪念版'];
const sideLabels = (count: LpCount) => Array.from({ length: count * 2 }, (_, index) => String.fromCharCode(65 + index));
const secondsFromDuration = (value: string) => { const [minutes, seconds] = value.split(':').map(Number); return Number.isFinite(minutes) && Number.isFinite(seconds) ? minutes * 60 + seconds : 0; };

export const ImportVinylModal: React.FC<ImportVinylModalProps> = ({ isOpen, onClose, onAddAlbum, onImportMultiple, currentAlbums }) => {
  const [method, setMethod] = useState<Method>('manual');
  const [title, setTitle] = useState(''); const [artist, setArtist] = useState(''); const [year, setYear] = useState(new Date().getFullYear()); const [label, setLabel] = useState('');
  const [coverUrl, setCoverUrl] = useState(''); const [urlOpen, setUrlOpen] = useState(false);
  const [vinylType, setVinylType] = useState<VinylType>('black'); const [vinylTexture, setVinylTexture] = useState('black'); const [primaryColor, setPrimaryColor] = useState('#d94438'); const [secondaryColor, setSecondaryColor] = useState('#f2d36b');
  const [rpm, setRpm] = useState<'33 ⅓ RPM' | '45 RPM' | '78 RPM'>('33 ⅓ RPM'); const [weight, setWeight] = useState('180g'); const [lpCount, setLpCount] = useState<LpCount>(1); const [edition, setEdition] = useState(''); const [editionNote, setEditionNote] = useState('');
  const [genre, setGenre] = useState<string[]>(['摇滚']); const [collectionTags, setCollectionTags] = useState<string[]>([]); const [tracksOpen, setTracksOpen] = useState(false); const [activeSide, setActiveSide] = useState('A'); const [sideTracks, setSideTracks] = useState<Record<string, Track[]>>({ A: [], B: [] });
  const [advancedOpen, setAdvancedOpen] = useState(false); const [matrixCode, setMatrixCode] = useState(''); const [catalogNumber, setCatalogNumber] = useState(''); const [country, setCountry] = useState(''); const [pressingPlant, setPressingPlant] = useState(''); const [barcodeValue, setBarcodeValue] = useState(''); const [purchaseDate, setPurchaseDate] = useState(''); const [price, setPrice] = useState<number | ''>(''); const [condition, setCondition] = useState('Near Mint (NM)'); const [sleeveCondition, setSleeveCondition] = useState('Near Mint (NM)'); const [notes, setNotes] = useState('');
  const [presetQuery, setPresetQuery] = useState(''); const [barcodeInput, setBarcodeInput] = useState(''); const [barcodeMessage, setBarcodeMessage] = useState(''); const [jsonText, setJsonText] = useState(''); const [batchError, setBatchError] = useState(''); const [batchSuccessCount, setBatchSuccessCount] = useState<number | null>(null); const [formError, setFormError] = useState('');
  const [isScanning, setIsScanning] = useState(false); const [isBarcodeLoading, setIsBarcodeLoading] = useState(false); const [isSaving, setIsSaving] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null); const pictureInputRef = useRef<HTMLInputElement>(null); const jsonFileInputRef = useRef<HTMLInputElement>(null); const dragIndexRef = useRef<number | null>(null);
  const scannerVideoRef = useRef<HTMLVideoElement>(null); const scannerControlsRef = useRef<IScannerControls | null>(null);
  const sides = useMemo(() => sideLabels(lpCount), [lpCount]); const activeDisc = Math.floor(sides.indexOf(activeSide) / 2) + 1; const activeTracks = sideTracks[activeSide] ?? []; const vinylOption = VINYL_TYPES.find(option => option.value === vinylType) ?? VINYL_TYPES[0];
  useEffect(() => () => scannerControlsRef.current?.stop(), []);
  if (!isOpen) return null;

  const setType = (option: typeof VINYL_TYPES[number]) => { setVinylType(option.value); setVinylTexture(option.texture ?? option.value); audioEngine.triggerHaptic('light'); };
  const updateLpCount = (count: LpCount) => { const nextSides = sideLabels(count); setLpCount(count); setSideTracks(current => Object.fromEntries(nextSides.map(side => [side, current[side] ?? []]))); if (!nextSides.includes(activeSide)) setActiveSide('A'); };
  const handleCoverFile = (file: File, picture = false) => { if (!file.type.startsWith('image/')) return setFormError('请选择 JPG、PNG 或 WEBP 图片'); const reader = new FileReader(); reader.onload = event => { if (typeof event.target?.result !== 'string') return; setCoverUrl(event.target.result); if (picture) setType(VINYL_TYPES.find(option => option.value === 'picture')!); }; reader.readAsDataURL(file); };
  const addTrack = () => setSideTracks(current => { const list = current[activeSide] ?? []; const number = list.length + 1; return { ...current, [activeSide]: [...list, { id: `trk-${Date.now()}-${activeSide}-${number}`, number, title: '', duration: '3:30', durationSec: 210 }] }; });
  const updateTrack = (index: number, field: 'title' | 'duration', value: string) => setSideTracks(current => ({ ...current, [activeSide]: (current[activeSide] ?? []).map((track, itemIndex) => itemIndex === index ? { ...track, [field]: value, ...(field === 'duration' ? { durationSec: secondsFromDuration(value) } : {}) } : track) }));
  const removeTrack = (index: number) => setSideTracks(current => ({ ...current, [activeSide]: (current[activeSide] ?? []).filter((_, itemIndex) => itemIndex !== index) }));
  const moveTrack = (from: number, to: number) => { if (from === to) return; setSideTracks(current => { const list = [...(current[activeSide] ?? [])]; const [item] = list.splice(from, 1); list.splice(to, 0, item); return { ...current, [activeSide]: list.map((track, index) => ({ ...track, number: index + 1 })) }; }); };
  const applyPreset = (preset: Partial<Album>) => { setTitle(preset.title ?? ''); setArtist(preset.artist ?? ''); setYear(preset.year ?? new Date().getFullYear()); setLabel(preset.label ?? ''); setCoverUrl(preset.coverUrl ?? ''); setRpm((preset.rpm as typeof rpm) ?? '33 ⅓ RPM'); setWeight(preset.weight ?? '180g'); setEdition(preset.edition ?? ''); setMatrixCode(preset.matrixCode ?? ''); setCatalogNumber(preset.catalogNumber ?? ''); setCountry(preset.country ?? ''); setPressingPlant(preset.pressingPlant ?? ''); setBarcodeValue(preset.barcode ?? ''); setGenre(preset.genre?.split(' · ') ?? ['其他']); setVinylType(preset.vinylType ?? preset.vinylVariant ?? 'black'); setVinylTexture(preset.vinylTexture ?? 'black'); const importedSides = preset.discs?.flatMap(record => record.sides) ?? [{ side: 'A', tracks: preset.tracks ?? [] }]; const count = Math.min(4, Math.max(1, Math.ceil(importedSides.length / 2))) as LpCount; setLpCount(count); setSideTracks(Object.fromEntries(sideLabels(count).map(side => [side, importedSides.find(item => item.side === side)?.tracks ?? []]))); setMethod('manual'); setTracksOpen(true); setFormError(''); audioEngine.triggerHaptic('medium'); };
  const handleBarcodeLookup = async (rawValue = barcodeInput) => { const cleaned = rawValue.replace(/\D/g, ''); if (!cleaned) return setBarcodeMessage('请输入或扫描封套上的 EAN / UPC 条码'); setBarcodeInput(cleaned); setBarcodeValue(cleaned); setBarcodeMessage(''); setIsBarcodeLoading(true); try { const match = await lookupVinylBarcode(cleaned); scannerControlsRef.current?.stop(); setIsScanning(false); applyPreset(match); setBarcodeValue(cleaned); } catch (error) { const fallback = BARCODE_PRESET_MAP[cleaned]; if (fallback) { applyPreset(fallback); setBarcodeValue(cleaned); } else { setBarcodeMessage(error instanceof Error ? error.message : '没有匹配到这张唱片'); } } finally { setIsBarcodeLoading(false); } };
  const startScanner = async () => { setBarcodeMessage(''); setIsScanning(true); await new Promise(requestAnimationFrame); if (!scannerVideoRef.current) return; try { const reader = new BrowserMultiFormatReader(); scannerControlsRef.current = await reader.decodeFromConstraints({ video: { facingMode: { ideal: 'environment' } }, audio: false }, scannerVideoRef.current, (result) => { if (!result) return; const value = result.getText(); scannerControlsRef.current?.stop(); setIsScanning(false); void handleBarcodeLookup(value); }); } catch { setIsScanning(false); setBarcodeMessage('无法打开摄像头，请允许相机权限，或手动输入条码。'); } };
  const stopScanner = () => { scannerControlsRef.current?.stop(); scannerControlsRef.current = null; setIsScanning(false); };
  const handleBatchJsonImport = async (rawText: string) => { setBatchError(''); try { const parsed = JSON.parse(rawText); const list = Array.isArray(parsed) ? parsed : [parsed]; if (!list.length) return setBatchError('没有识别到可导入的唱片数据'); const sanitized: Album[] = list.map((item, index) => ({ id: item.id || `imported-${Date.now()}-${index}`, title: item.title || '未命名唱片', artist: item.artist || '未知艺术家', artistId: item.artistId || 'artist-unknown', year: Number(item.year) || new Date().getFullYear(), genre: item.genre || '其他', coverUrl: item.coverUrl || '', label: item.label || '未知厂牌', rpm: item.rpm || '33 ⅓ RPM', weight: item.weight || '标准', edition: item.edition || '标准版', matrixCode: item.matrixCode || '', price: Number(item.price) || undefined, trackCount: item.tracks?.length || 0, totalDuration: item.totalDuration || '0:00', description: item.description || '', color: item.color || '#131316', isCollected: true, condition: item.condition || 'Near Mint (NM)', tracks: Array.isArray(item.tracks) ? item.tracks : [], discs: Array.isArray(item.discs) ? item.discs : undefined, addedAt: new Date().toISOString().split('T')[0] })); setIsSaving(true); await onImportMultiple(sanitized); setBatchSuccessCount(sanitized.length); audioEngine.triggerHaptic('medium'); } catch (error) { setBatchError(error instanceof Error ? error.message : 'JSON 无法解析或后端保存失败'); } finally { setIsSaving(false); } };
  const handleExportJson = () => { const anchor = document.createElement('a'); anchor.href = `data:application/json;charset=utf-8,${encodeURIComponent(JSON.stringify(currentAlbums, null, 2))}`; anchor.download = `vinyl_collection_${new Date().toISOString().split('T')[0]}.json`; document.body.appendChild(anchor); anchor.click(); anchor.remove(); };
  const handleManualSubmit = async (event: React.FormEvent) => { event.preventDefault(); if (!title.trim() || !artist.trim()) { setFormError('请先填写专辑名称和艺术家'); document.querySelector<HTMLInputElement>(!title.trim() ? '#add-vinyl-title' : '#add-vinyl-artist')?.focus(); return; } const flatTracks = sides.flatMap(side => (sideTracks[side] ?? []).map((track, index) => ({ ...track, number: index + 1 }))); const totalSeconds = flatTracks.reduce((sum, track) => sum + track.durationSec, 0); const discs = Array.from({ length: lpCount }, (_, index) => ({ disc: index + 1, sides: sides.slice(index * 2, index * 2 + 2).map(side => ({ side, tracks: sideTracks[side] ?? [] })) })); setIsSaving(true); setFormError(''); try { await onAddAlbum({ id: `imported-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, title: title.trim(), artist: artist.trim(), artistId: artist.toLowerCase().trim().replace(/\s+/g, '-'), year: Number(year) || new Date().getFullYear(), genre: genre.join(' · ') || '其他', coverUrl, label: label.trim() || '未知厂牌', rpm, weight, edition: edition.trim() || `${lpCount}LP 收藏版`, matrixCode, price: price === '' ? undefined : Number(price), trackCount: flatTracks.length, totalDuration: `${Math.floor(totalSeconds / 60)}:${String(totalSeconds % 60).padStart(2, '0')}`, description: [editionNote, notes].filter(Boolean).join('\n'), color: primaryColor, tracks: flatTracks, discs, isCollected: true, condition, waxColor: vinylOption.label, vinylType, vinylTexture, vinylColor: primaryColor, vinylSecondaryColor: secondaryColor, vinylColors: [primaryColor, secondaryColor], addedAt: purchaseDate || new Date().toISOString().split('T')[0], barcode: barcodeValue || undefined, catalogNumber, country, pressingPlant, sleeveCondition, collectionTags }); audioEngine.triggerHaptic('medium'); onClose(); } catch (error) { setFormError(error instanceof Error ? error.message : '后端保存失败，请稍后重试'); } finally { setIsSaving(false); } };
  const toggleListValue = (value: string, values: string[], setter: React.Dispatch<React.SetStateAction<string[]>>) => setter(values.includes(value) ? values.filter(item => item !== value) : [...values, value]);

  return <section id="import-vinyl-modal" className="add-vinyl" role="dialog" aria-modal="true" aria-labelledby="add-vinyl-title-heading">
    <header className="add-vinyl__header"><button type="button" onClick={onClose} aria-label="返回收藏"><ArrowLeft /></button><div><h2 id="add-vinyl-title-heading">新增唱片</h2><p>添加到你的黑胶收藏</p></div><span aria-hidden="true" /></header>
    <div className="add-vinyl__scroll"><nav className="add-vinyl__methods" aria-label="录入方式">{METHODS.map(item => { const Icon = item.icon; return <button key={item.id} type="button" className={method === item.id ? 'is-active' : ''} aria-pressed={method === item.id} onClick={() => setMethod(item.id)}><Icon /><span>{item.label}</span></button>; })}</nav>
      {method === 'manual' && <form id="add-vinyl-form" className="add-vinyl__form" onSubmit={handleManualSubmit}>
        <section className="vinyl-entry-preview" aria-labelledby="vinyl-preview-heading"><div className="add-section__heading"><div><h3 id="vinyl-preview-heading">唱片预览</h3><p>封套与压片效果会同步更新</p></div><Disc3 /></div><div className="vinyl-entry-preview__stage"><div className="vinyl-entry-preview__disc"><VinylDisc coverUrl={coverUrl} albumTitle={title || '未命名唱片'} artistName={artist} size="174px" type={vinylType} texture={vinylTexture} vinylColors={[primaryColor, secondaryColor]} labelImage={coverUrl || undefined} /></div><button type="button" className="vinyl-entry-preview__sleeve" onClick={() => fileInputRef.current?.click()} aria-label={coverUrl ? '修改封面' : '上传封面'}>{coverUrl ? <AlbumSleeve coverUrl={coverUrl} title={title || '唱片封面'} size="164px" /> : <span className="vinyl-entry-preview__placeholder"><ImagePlus /><strong>上传封面</strong><small>JPG、PNG、WEBP</small></span>}{coverUrl && <span className="vinyl-entry-preview__edit"><Pencil /></span>}</button><input ref={fileInputRef} type="file" accept="image/*" hidden onChange={event => event.target.files?.[0] && handleCoverFile(event.target.files[0])} /></div><button type="button" className="add-vinyl__quiet-link" onClick={() => setUrlOpen(value => !value)} aria-expanded={urlOpen}><Link2 />图片链接（可选）<ChevronDown className={urlOpen ? 'is-open' : ''} /></button>{urlOpen && <label className="add-field"><span>封面图片链接</span><input type="url" value={coverUrl} onChange={event => setCoverUrl(event.target.value)} placeholder="https://example.com/cover.jpg" /></label>}</section>
        <section className="add-section" aria-labelledby="basic-info-heading"><div className="add-section__heading"><div><h3 id="basic-info-heading">基础信息</h3><p>先记录这张唱片是谁的作品</p></div></div><div className="add-field-grid"><label className="add-field"><span>专辑名称 <i>*</i></span><input id="add-vinyl-title" required value={title} onChange={event => setTitle(event.target.value)} placeholder="例如：Kind of Blue" /></label><label className="add-field"><span>艺术家 / 乐团 <i>*</i></span><input id="add-vinyl-artist" required value={artist} onChange={event => setArtist(event.target.value)} placeholder="例如：Miles Davis" /></label><label className="add-field"><span>发行年份</span><input type="number" inputMode="numeric" value={year} onChange={event => setYear(Number(event.target.value))} /></label><label className="add-field"><span>厂牌 / 压盘厂</span><input value={label} onChange={event => setLabel(event.target.value)} placeholder="例如：Columbia Records" /></label></div></section>
        <section className="add-section" aria-labelledby="edition-heading"><div className="add-section__heading"><div><h3 id="edition-heading">唱片版本</h3><p>记录这张实体压片的规格</p></div></div><fieldset className="add-choice-group"><legend>唱片类型</legend><div className="add-choice-grid">{VINYL_TYPES.map(option => <button key={option.value} type="button" className={vinylType === option.value ? 'is-selected' : ''} onClick={() => setType(option)}><span className="add-choice__disc" data-texture={option.texture ?? option.value} /><span>{option.label}</span></button>)}</div></fieldset>{(vinylType === 'colored' || vinylType === 'split') && <div className="add-color-row"><label><span>主色</span><input type="color" value={primaryColor} onChange={event => setPrimaryColor(event.target.value)} /></label>{vinylType === 'split' && <label><span>副色</span><input type="color" value={secondaryColor} onChange={event => setSecondaryColor(event.target.value)} /></label>}</div>}{(vinylType === 'marble' || vinylType === 'splatter' || vinylType === 'liquid') && <label className="add-field"><span>纹理</span><select value={vinylTexture} onChange={event => setVinylTexture(event.target.value)}>{vinylType === 'marble' && <><option value="marbled-01">烟云纹</option><option value="marbled-02">矿石纹</option></>}{vinylType === 'splatter' && <><option value="splatter-01">亮色泼墨</option><option value="splatter-02">深色泼墨</option></>}{vinylType === 'liquid' && <><option value="liquid-01">流体一</option><option value="liquid-02">流体二</option></>}</select></label>}{vinylType === 'picture' && <><button type="button" className="add-vinyl__upload-picture" onClick={() => pictureInputRef.current?.click()}><Upload />上传 Picture Disc 图案</button><input ref={pictureInputRef} type="file" accept="image/*" hidden onChange={event => event.target.files?.[0] && handleCoverFile(event.target.files[0], true)} /></>}<div className="add-segment-row"><fieldset><legend>转速</legend><div>{(['33 ⅓ RPM', '45 RPM', '78 RPM'] as const).map(value => <button key={value} type="button" className={rpm === value ? 'is-selected' : ''} onClick={() => setRpm(value)}>{value}</button>)}</div></fieldset><fieldset><legend>重量</legend><div>{['标准', '140g', '180g', '200g'].map(value => <button key={value} type="button" className={weight === value ? 'is-selected' : ''} onClick={() => setWeight(value)}>{value}</button>)}</div></fieldset><fieldset><legend>唱片数量</legend><div>{([1, 2, 3] as const).map(value => <button key={value} type="button" className={lpCount === value ? 'is-selected' : ''} onClick={() => updateLpCount(value)}>{value}LP</button>)}</div></fieldset></div><div className="add-field-grid"><label className="add-field"><span>版本名称</span><input value={edition} onChange={event => setEdition(event.target.value)} placeholder="例如：50 周年重制版" /></label><label className="add-field"><span>版本备注</span><input value={editionNote} onChange={event => setEditionNote(event.target.value)} placeholder="母带、编号或包装特征" /></label></div></section>
        <section className="add-section add-section--collapsible" aria-labelledby="tracks-heading"><button type="button" className="add-section__toggle" onClick={() => setTracksOpen(value => !value)} aria-expanded={tracksOpen}><span><strong id="tracks-heading">曲目与唱片面</strong><small>可稍后补充</small></span><ChevronDown className={tracksOpen ? 'is-open' : ''} /></button>{tracksOpen && <div className="track-editor"><div className="track-editor__discs">{Array.from({ length: lpCount }, (_, index) => <button key={index} type="button" className={activeDisc === index + 1 ? 'is-selected' : ''} onClick={() => setActiveSide(sides[index * 2])}>Disc {index + 1}</button>)}</div><div className="track-editor__sides">{sides.slice((activeDisc - 1) * 2, activeDisc * 2).map(side => <button key={side} type="button" className={activeSide === side ? 'is-selected' : ''} onClick={() => setActiveSide(side)}>Side {side}</button>)}</div><div className="track-editor__list">{activeTracks.length ? activeTracks.map((track, index) => <div className="track-row" key={track.id} draggable onDragStart={() => { dragIndexRef.current = index; }} onDragOver={event => event.preventDefault()} onDrop={() => { if (dragIndexRef.current !== null) moveTrack(dragIndexRef.current, index); dragIndexRef.current = null; }}><GripVertical /><span>{activeSide}{index + 1}</span><input value={track.title} onChange={event => updateTrack(index, 'title', event.target.value)} placeholder="歌曲名" aria-label={`${activeSide}${index + 1} 歌曲名`} /><input value={track.duration} onChange={event => updateTrack(index, 'duration', event.target.value)} placeholder="3:30" aria-label={`${activeSide}${index + 1} 时长`} /><button type="button" onClick={() => removeTrack(index)} aria-label={`删除 ${activeSide}${index + 1}`}><Trash2 /></button></div>) : <p className="track-editor__empty">Side {activeSide} 还没有曲目</p>}</div><button type="button" className="track-editor__add" onClick={addTrack}><Plus />添加曲目</button></div>}</section>
        <section className="add-section" aria-labelledby="category-heading"><div className="add-section__heading"><div><h3 id="category-heading">分类</h3><p>音乐流派与收藏属性分开记录</p></div></div><fieldset className="add-chip-group"><legend>流派</legend><div>{GENRES.map(item => <button key={item} type="button" className={genre.includes(item) ? 'is-selected' : ''} onClick={() => toggleListValue(item, genre, setGenre)}>{item}</button>)}</div></fieldset><fieldset className="add-chip-group"><legend>收藏标签</legend><div>{COLLECTION_TAGS.map(item => <button key={item} type="button" className={collectionTags.includes(item) ? 'is-selected' : ''} onClick={() => toggleListValue(item, collectionTags, setCollectionTags)}>{item}</button>)}</div></fieldset></section>
        <section className="add-section add-section--collapsible"><button type="button" className="add-section__toggle" onClick={() => setAdvancedOpen(value => !value)} aria-expanded={advancedOpen}><span><strong>更多档案信息</strong><small>编号、购买与品相</small></span><ChevronDown className={advancedOpen ? 'is-open' : ''} /></button>{advancedOpen && <div className="add-field-grid add-field-grid--advanced"><label className="add-field"><span>Matrix Code</span><input value={matrixCode} onChange={event => setMatrixCode(event.target.value)} /></label><label className="add-field"><span>Catalog Number</span><input value={catalogNumber} onChange={event => setCatalogNumber(event.target.value)} /></label><label className="add-field"><span>国家 / 地区</span><input value={country} onChange={event => setCountry(event.target.value)} /></label><label className="add-field"><span>压片厂</span><input value={pressingPlant} onChange={event => setPressingPlant(event.target.value)} /></label><label className="add-field"><span>条码</span><input value={barcodeValue} onChange={event => setBarcodeValue(event.target.value)} inputMode="numeric" /></label><label className="add-field"><span>购买日期</span><input type="date" value={purchaseDate} onChange={event => setPurchaseDate(event.target.value)} /></label><label className="add-field"><span>购买价格</span><input type="number" value={price} onChange={event => setPrice(event.target.value ? Number(event.target.value) : '')} inputMode="decimal" /></label><label className="add-field"><span>唱片成色</span><select value={condition} onChange={event => setCondition(event.target.value)}><option>Mint (M)</option><option>Near Mint (NM)</option><option>Very Good Plus (VG+)</option><option>Very Good (VG)</option></select></label><label className="add-field"><span>封套成色</span><select value={sleeveCondition} onChange={event => setSleeveCondition(event.target.value)}><option>Mint (M)</option><option>Near Mint (NM)</option><option>Very Good Plus (VG+)</option><option>Very Good (VG)</option></select></label><label className="add-field add-field--wide"><span>备注</span><textarea value={notes} onChange={event => setNotes(event.target.value)} rows={3} /></label></div>}</section>{formError && <p className="add-vinyl__error" role="alert">{formError}</p>}
      </form>}
      {method === 'presets' && <section className="add-mode-page"><div className="add-mode-page__intro"><Library /><h3>从母盘库查找</h3><p>选择母盘后自动填充封面、基础资料、曲目与唱片面。</p></div><label className="add-mode-search"><Search /><input value={presetQuery} onChange={event => setPresetQuery(event.target.value)} placeholder="搜索专辑或艺术家" /></label><div className="master-list">{PRESET_IMPORT_VINYLS.filter(item => `${item.title} ${item.artist}`.toLowerCase().includes(presetQuery.toLowerCase())).map(preset => <button type="button" key={preset.id} onClick={() => applyPreset(preset)}><img src={preset.coverUrl} alt="" /><span><strong>{preset.title}</strong><small>{preset.artist} · {preset.year}</small><em>{preset.rpm} · {preset.weight}</em></span><Plus /></button>)}</div></section>}
      {method === 'barcode' && <section className="add-mode-page add-mode-page--center"><div className={`barcode-stage ${isScanning ? 'is-scanning' : ''}`}>{isScanning ? <video ref={scannerVideoRef} muted playsInline aria-label="条码扫描摄像头" /> : <Barcode />}<span className="barcode-stage__line" /></div><div className="add-mode-page__intro"><h3>扫描封套条码</h3><p>识别 EAN / UPC，并从 MusicBrainz 查询真实发行版本。</p></div><button type="button" className="camera-toggle" onClick={isScanning ? stopScanner : startScanner}>{isScanning ? <CameraOff /> : <Camera />}{isScanning ? '关闭摄像头' : '打开摄像头扫码'}</button><div className="barcode-divider"><span>或手动输入</span></div><label className="add-mode-search"><Barcode /><input value={barcodeInput} onChange={event => setBarcodeInput(event.target.value)} inputMode="numeric" placeholder="输入 8–14 位 EAN / UPC" /></label><button type="button" className="add-mode-primary" disabled={isBarcodeLoading} onClick={() => void handleBarcodeLookup()}>{isBarcodeLoading && <LoaderCircle className="is-spinning" />}{isBarcodeLoading ? '正在查询唱片库' : '查询唱片'}</button>{barcodeMessage && <div className="add-mode-message"><p>{barcodeMessage}</p><button type="button" onClick={() => setMethod('manual')}>保留条码并手动录入</button></div>}</section>}
      {method === 'batch' && <section className="add-mode-page"><div className="add-mode-page__intro"><FileJson /><h3>导入 JSON</h3><p>适合迁移已有唱片库，普通录入无需使用。</p></div><button type="button" className="json-upload" onClick={() => jsonFileInputRef.current?.click()}><Upload /><strong>上传 JSON 文件</strong><small>支持单张或批量唱片数据</small></button><input ref={jsonFileInputRef} type="file" accept=".json,application/json" hidden onChange={event => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = item => setJsonText(String(item.target?.result ?? '')); reader.readAsText(file); }} /><label className="add-field"><span>粘贴 JSON</span><textarea rows={9} value={jsonText} onChange={event => setJsonText(event.target.value)} placeholder='[{ "title": "Abbey Road", "artist": "The Beatles" }]' /></label>{batchError && <p className="add-vinyl__error" role="alert">{batchError}</p>}{batchSuccessCount !== null && <p className="add-vinyl__success"><Check />已导入 {batchSuccessCount} 张唱片并保存到后端</p>}<div className="json-actions"><button type="button" onClick={handleExportJson}><Download />下载当前唱片库</button><button type="button" className="add-mode-primary" disabled={!jsonText.trim() || isSaving} onClick={() => void handleBatchJsonImport(jsonText)}>{isSaving ? '正在保存' : '导入并保存'}</button></div></section>}
    </div>
    <footer className="add-vinyl__bottom"><button type="button" onClick={onClose}>取消</button>{method === 'manual' && <button type="submit" form="add-vinyl-form" className="is-primary" disabled={isSaving}>{isSaving ? <LoaderCircle className="is-spinning" /> : <Disc3 />}{isSaving ? '正在保存到后端' : '保存唱片'}</button>}</footer>
  </section>;
};
